Release 1.0.1 		_ logging repeat compression is now by channel instead of global
	Fixes:
                _ fixed an issue where glibc whould assert if libgcc_s.so (libgcc_s.so.1) and libc.so (libc.so.6) where not
		  available inside the chrooted directory of YADIFA
		_ fixed an issue in the syslog module

	Known issues:
		_ on 32 bits architectures, the sig-validity-* fields are not properly copied from <main> to <zone>
		  as a workaround, set the sig-validity fields in each <zone> container in 32 bits architectures

		  ie:
			  sig-validity-interval 7
 			  sig-validity-regeneration 168
			  sig-validity-jitter 3600
		_ if the serial of a zone is changed in a way that it goes beyond a value such as
		  the journal serial start is bigger than the journal serial end, issues are expected
		  for IXFR answers.
		_ notify is ignored on TCP

diff --git a/etc/yadifad.init b/etc/yadifad.init
--- a/etc/yadifad.init
+++ b/etc/yadifad.init
@@ -17,38 +17,22 @@
 
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
-PREFIX="/usr/local"
+PREFIX="/registry/yadifa"
 NAME="yadifad"
-
 NAMED_USERNAME="nobody"
-
 DAEMON="/sbin/${NAME}"
 
-VAR="$PREFIX/var"
-CONF="$PREFIX/etc/yadifad.conf"
-
-PIDFILE="${PREFIX}/var/run/yadifa.pid"
 SCRIPTNAME="/etc/init.d/${NAME}"
+PIDFILE="$PREFIX/var/run/yadifa.pid"
 
-if [ "$MAX_STOP_WAIT" = "" ]
-then
-	MAX_STOP_WAIT=60
-fi
+CHROOTS=0
+CHROOTDIR=$PREFIX
+YADIFA_CHROOT=/var
 
 if [ "$DEBUG" = "" ]
 then
 	DEBUG=0
 fi
-
-if [ "$DUMPS_CORE" = "" ]
-then
-	DUMPS_CORE=0
-fi
-
-# not yet:
-#
-# CHECK="/sbin/yadifa-checkconf"
-
 
 log()
 {
@@ -64,6 +48,45 @@ debug()
 		logger -t $NAME-init-script -- $*
 	fi
 }
+
+if [ $CHROOTS -ne 0 ]
+then
+	PREFIX=
+fi
+
+VAR="$PREFIX/var"
+CONF="$PREFIX/etc/yadifad.conf"
+
+if [ "$MAX_STOP_WAIT" = "" ]
+then
+	MAX_STOP_WAIT=5
+fi
+
+# Inside the internal chroot
+
+if [ "$CORE_PREFIX" = "" ]
+then
+	CORE_PREFIX=/log
+fi
+
+if [ "$DUMPS_CORE" = "" ]
+then
+	DUMPS_CORE=1
+fi
+
+if [ $DUMPS_CORE -ne 0 ]
+then
+	if [ ! -d $CHROOTDIR/$YADIFA_CHROOT/$CORE_PREFIX ]
+	then
+		log "Core dump enabled but '$CHROOTDIR/$YADIFA_CHROOT/$CORE_PREFIX' directory does not exists"
+		exit 1
+	fi
+fi
+
+# not yet:
+#
+# CHECK="/sbin/yadifa-checkconf"
+
 
 # $? : supposed to be set
 # 1  : message
@@ -87,9 +110,59 @@ die_on_error()
         		$3
 	        fi
 	        
-                log "Error: '$1' ($ERR)"
+                log "error: '$1' ($ERR)"
                 exit $err
         fi
+}
+
+#
+# Function that checks if yadifa is running
+#
+
+do_status_internal()
+{
+	debug "checking for valid PIDFILE ${PIDFILE}"
+
+	running=0
+
+	if [ -f ${PIDFILE} ]
+	then
+		PID=$(cat ${PIDFILE})
+
+		if [ "${PID}" != "" ]
+		then
+			PROC=$(ps -p ${PID} | tail -1| awk '{print $4}')
+
+			if [ "$PROC" = "$NAME" ]
+			then
+				running=1
+			else
+				log "error : process with pid ${PID} is '$PROC' and not '$NAME' : deleting pid file"
+				rm -f ${PIDFILE}
+			fi
+		else
+			log "error: empty '${PIDFILE}' : deleting pid file"
+			rm -f ${PIDFILE}
+		fi
+	fi
+
+	return $running
+}
+
+do_status()
+{
+	do_status_internal
+
+	running=$?
+	
+	if [ $running -eq 1 ]
+	then
+		log "${NAME} seems to be already running."
+		exit 0
+	else
+		log "${NAME} does not seem to be running."
+		exit 1
+	fi
 }
 
 #
@@ -101,40 +174,49 @@ do_start()
 
 	debug "starting if no valid PIDFILE ${PIDFILE}"
 
-	if [ -f ${PIDFILE} ]
-	then
-		kill -0 $(cat ${PIDFILE})
-		
-		if [ $? -eq 0 ]
-		then
-			echo "${NAME} seems to be already running."
-			echo "reason: ${PIDFILE} exists"
-			exit 1
-		fi
+	do_status_internal
 
-		rm ${PIDFILE}
+	running=$?
+
+	if [ $running -eq 1 ]
+	then
+		log "${NAME} seems to be already running."
+		exit 1
 	fi
 	
-	debug cd ${PREFIX}${JAIL}
-	cd ${PREFIX}${JAIL}
+	debug cd $CHROOTDIR/${PREFIX}
+	cd $CHROOTDIR/${PREFIX}
 
 	debug prefix = ${PREFIX}
 	debug daemon = ${DAEMON}
 
 	if [ $DUMPS_CORE -ne 0 ]
 	then
+		COREPATH="$CHROOTDIR/$YADIFA_CHROOT/$CORE_PREFIX/cores"
+
+		log "enabling core dump in $COREPATH"
+
 		ulimit -c unlimited
 
-		mkdir -p /tmp/cores
-		chmod 0777 /tmp/cores
-		chmod +t /tmp/cores
-		echo "/tmp/cores/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern
+
+		mkdir -p $COREPATH
+		chmod 0777 $COREPATH
+		chmod +t $COREPATH
+
+		log "core dump will be stored in '$COREPATH' ($CORE_PREFIX/cores)"
+
+		echo "$CORE_PREFIX/cores/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern
 		echo 0x7 > /proc/self/coredump_filter
 		echo -n 1 > /proc/sys/kernel/core_uses_pid
 		echo -n 1 > /proc/sys/fs/suid_dumpable
 	fi
 
 	CMD="${PREFIX}${DAEMON} -c ${CONF}"
+	
+	if [ $CHROOTS -ne 0 ]
+	then
+		CMD="chroot $CHROOTDIR $CMD"
+	fi
 
 	debug $CMD
 
@@ -145,35 +227,6 @@ do_start()
 	exit 0
 }
 
-#
-# Function that checks if yadifa is running
-#
-
-do_status()
-{
-	log "checking for valid PIDFILE ${PIDFILE}"
-
-	if [ -f ${PIDFILE} ]
-	then
-		kill -0 $(cat ${PIDFILE})
-		
-		if [ $? -eq 0 ]
-		then
-			log "${NAME} seems to be already running."
-			debug "reason: ${PIDFILE} exists and a process with its pid is running"
-			exit 0
-		fi
-
-		debug "cleaning old pid file ${PIDFILE}"
-
-		rm ${PIDFILE}
-	fi
-
-	log "${NAME} does not seem to be running."
-	debug "reason: ${PIDFILE} does not exists"
-
-	exit 1
-}
 
 #
 # Function that stops the daemon/service
@@ -186,28 +239,52 @@ do_stop()
 
 	if [ -f ${PIDFILE} ]
 	then
-		PID=$(cat ${PIDFILE})
-		kill ${PID} 
-				
-		die_on_error "Unable to kill process with PID ${PID}" $? "rm -f ${PIDFILE}"
+		while [ -f ${PIDFILE} ]
+		do
+			PID=$(cat ${PIDFILE})
+
+			if [ "${PID}" = "" ]
+			then
+				log "error: empty '${PIDFILE}' : deleting pid file"
+				rm -f ${PIDFILE}
+				break
+			fi
+
+			PROC=$(ps -p ${PID} | tail -1| awk '{print $4}')
+
+			if [ "$PROC" != "$NAME" ]
+			then
+				log "error : process with pid ${PID} is '$PROC' and not '$NAME' : deleting pid file"
+				rm -f ${PIDFILE}
+				break
+			fi
+
+			kill ${PID} > /dev/null 2>&1
+
+			for count in $(seq 0 $MAX_STOP_WAIT)
+			do
+				if [ ! -f ${PIDFILE} ]
+				then
+					break
+				fi
+
+				kill -0 ${PID} > /dev/null 2>&1
+
+				if [ $? -ne 0 ]
+				then
+					rm -f ${PIDFILE}
+					break
+				fi
+
+				log "waiting for the process to stop (waited $count seconds)"
+
+				sleep 1
+			done
+		done
 	else
 		log "${NAME} does not seem to be running ..."
 		debug "reason: ${PIDFILE} not found"
 	fi
-}
-
-do_waitstop()
-{
-	for count in $(seq 0 $MAX_STOP_WAIT)
-	do
-		if [ ! -f ${PIDFILE} ]
-		then
-			break
-		fi
-
-		log "Waiting for the process to stop (waited $count seconds)";
-		sleep 1
-	done
 }
 
 debug called with $1
@@ -218,11 +295,9 @@ case "$1" in
 	;;
   stop)
 	do_stop
-	do_waitstop
 	;;
   restart)
 	do_stop
-	do_waitstop
 	do_start
 	;;
   status)
